badyet/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('', include('transactions.urls')),
]

transactions/urls.py
from django.urls import path
from . import views

app_name = 'transactions'

urlpatterns = [
    path('add_transaction/', views.add_transaction, name='add_transaction'),
    path('transaction_list/<int:user_id>/', views.transaction_list, name='transaction_list'),
]

users/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views

urlpatterns = [
    path('', views.profile_view, name='profile'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('register/', views.register_view, name='register'),
    path('edit/', views.edit_profile, name='edit_profile'),
    path('delete_transaction/<int:transaction_id>/', views.delete_transaction, name='delete_transaction'),
]

transactions/models.py
from django.db import models
from django.contrib.auth.models import User
# from goals.models import Goal

class Category(models.Model):
    name = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.name

class Transaction(models.Model):
    name = models.CharField(max_length=100, default='Sample Transaction')
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    date = models.DateField()
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name
# class Income(Transaction):
#     savings_goal = models.ForeignKey(Goal, on_delete=models.SET_NULL, blank=True, null=True)

users/models.py
from django.contrib.auth.models import User
from django.db import models

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    email = models.EmailField()
    phone = models.CharField(max_length=15)

transactions/forms.py
from .models import Transaction
from django import forms

# class IncomeForm(forms.ModelForm):
#     class Meta:
#         model = Income
#         fields = ['amount', 'date', 'category', 'description', 'savings_goal']

# class ExpenseForm(forms.ModelForm):
#     class Meta:
#         model = Expense
#         fields = ['amount', 'date', 'category', 'description', 'payment_method', 'is_recurring']

class TransactionForm(forms.ModelForm):
    class Meta:
        model = Transaction
        fields = ['name', 'amount', 'date', 'category', 'description']

users/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import UserProfile

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['phone']

class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Repeat password', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email']

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('Passwords don\'t match.')
        return cd['password2']

class EmailForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['email']

transactions/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.http import Http404
from .models import Transaction
from .forms import TransactionForm

def add_transaction(request):
    if request.method == 'POST':
        form = TransactionForm(request.POST)
        if form.is_valid():
            transaction = form.save(commit=False)
            transaction.user = request.user
            transaction.save()
            return redirect('transactions:transaction_list', user_id=request.user.id)
    else:
        form = TransactionForm()
    return render(request, 'transactions/add_transaction.html', {'form': form})

@login_required
def transaction_list(request, user_id):
    transactions = Transaction.objects.filter(user_id=user_id)
    return render(request, 'transactions/transaction_list.html', {'transactions': transactions})

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from .forms import UserProfileForm, UserRegistrationForm, EmailForm
from .models import UserProfile
from transactions.models import Transaction

def login_view(request):
    if request.user.is_authenticated:
        return redirect('profile')
    
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('profile')
    else:
        form = AuthenticationForm()
    return render(request, 'users/login.html', {'form': form})

def logout_view(request):
    logout(request)
    return redirect('login')

@login_required
def profile_view(request):
    user = request.user
    user_profile = UserProfile.objects.get(user=user)
    transactions = Transaction.objects.filter(user=user)
    return render(request, 'users/profile.html', {'user_profile': user_profile, 'transactions': transactions})

def register_view(request):
    if request.method == 'POST':
        user_form = UserRegistrationForm(request.POST)
        profile_form = UserProfileForm(request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            new_user = user_form.save(commit=False)
            new_user.set_password(user_form.cleaned_data['password'])
            new_user.save()
            profile = profile_form.save(commit=False)
            profile.user = new_user
            profile.save()
            return redirect('login')
    else:
        user_form = UserRegistrationForm()
        profile_form = UserProfileForm() 
    return render(request, 'users/register.html', {'user_form': user_form, 'profile_form': profile_form})

@login_required
def edit_profile(request):
    try:
        profile = request.user.userprofile
    except UserProfile.DoesNotExist:
        profile = None

    try:
        user_email = request.user.email
    except User.DoesNotExist:
        user_email = None

    if request.method == 'POST':
        profile_form = UserProfileForm(request.POST, instance=profile)
        email_form = EmailForm(request.POST, instance=request.user)
        if profile_form.is_valid() and email_form.is_valid():
            profile = profile_form.save(commit=False)
            profile.user = request.user
            profile.save()
            email_form.save()
            return redirect('profile')
    else:
        profile_form = UserProfileForm(instance=profile)
        email_form = EmailForm(instance=request.user, initial={'email': user_email})
    return render(request, 'users/edit.html', {'profile_form': profile_form, 'email_form': email_form})

@login_required
def delete_transaction(request, transaction_id):
    try:
        transaction = Transaction.objects.get(id=transaction_id, user=request.user)
        transaction.delete()
    except Transaction.DoesNotExist:
        # Handle if transaction does not exist or if user is not the owner
        pass  # You can handle this according to your application logic
    return redirect('profile')

transactions/templates/transactions/add_transaction.html
{% extends 'transactions/base.html' %}
{% block content %}

<div class="header">
    <h2>Add Transaction</h2>
</div>

<div class="form-group">
    <form method="post">
        {% csrf_token %}
        <label>{{ form.name.label }}</label>
        {{ form.name }}
        <label>{{ form.amount.label }}</label>
        {{ form.amount }}
        <label>{{ form.date.label }}</label>
        <input type="date" name="date" id="id_date">
        <!-- {{ form.date }} -->
        <label>{{ form.category.label }}</label>
        {{ form.category }}
        <label>{{ form.description.label }}</label>
        {{ form.description }}
        <br>
        <input style="margin-top: 5px;" class="button" type="submit" value="Save">
    </form>
</div>

{% endblock content %}

transactions/templates/transactions/base.html
{% load static %}

<!DOCTYPE html>
<head>
    <title>Badyet</title>

    <link href="{% static 'css/main.css' %}" 
    rel="stylesheet" 
    type="text/css">

    <link rel="icon" type="image/jpg" href="{% static 'images/badyet.jpg' %}">

</head>
<body>

    <div class="container">
        {% block content %}

        {% endblock content %}
    </div>
</body>
</html>

transactions/templates/transactions/transaction_list.html
{% extends 'transactions/base.html' %}
{% block content %}

<div class="header">
    <h2>Transactions</h2>
</div>

<div class="transaction-list">
    {% for transaction in transactions %}
        <div class="transaction-item">
            <div class="transaction-name">
                <a href="">{{ transaction.name }}</a>
            </div>
        </div>
    {% empty %}
        <div class="no-transactions">
            No transactions found.
        </div>
    {% endfor %}
</div>
<a href="{% url 'transactions:add_transaction' %}">Add Transaction</a>

{% endblock content %}

users/templates/users/edit.html
{% extends 'users/base.html' %}
{% block content %}

<div class="header">
  <div>
    <a style="font-size: 20px; text-decoration: none; color: #fff;" href="{% url 'profile' %}">&#x25C4;</a>
  </div>
</div>

<div class="form-group">
  <form method="post">
    {% csrf_token %}
    <div>
      <label>Phone</label>
      {{ profile_form.phone }}
    </div>
    <div>
      {{ email_form.email.label_tag }}
      {{ email_form.email }}
    </div>
    <input style="margin-top: 15px;" class="button" type="submit" value="Save Changes">
  </form>
</div>

{% endblock content %}

users/templates/users/login.html
{% extends 'users/base.html' %}
{% load static %}
{% block content %}

<div class="header">
    <!-- <img class="logo" src="{% static 'images/badyet.jpg' %}" alt="Logo"> -->
    <h2>Login</h2>
</div>

<div class="form-group">
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}

    <button style="margin-top: 5px;" class="button" type="submit">Login</button>
    <br>
    <p>Don't have an account? <a href="{% url 'register' %}">Register</a></p>
  </form>
</div>

{% endblock content %}

users/templates/users/profile.html
{% extends 'users/base.html' %}
{% block content %}

<div class="header">
    <h2>Welcome, {{ user.username|title }}</h2>
</div>

<div class="form-group">
    <a href="{% url 'logout' %}">Logout</a>
    <a href="{% url 'edit_profile' %}">Edit Profile</a>
    
    <p>Email: {{ user.email }}</p>
    <p>Phone: {{ user.userprofile.phone }}</p>
</div>

{% endblock content %}

users/templates/users/register.html
{% extends 'users/base.html' %}
{% block content %}

<div class="header">
  <h2>Register</h2>
</div>

<div class="form-group">
  <form method="post">
    {% csrf_token %}
    <label>{{ user_form.username.label }}</label>
    {{ user_form.username }}
    <label>{{ user_form.email.label }}</label>
    {{ user_form.email }}
    <label>{{ profile_form.phone.label }}</label>
    {{ profile_form.phone }}
    <label>{{ user_form.password.label }}</label>
    {{ user_form.password }}
    <label>{{ user_form.password2.label }}</label>
    {{ user_form.password2 }}
    <input style="margin-top: 5px;" class="button" type="submit" value="Register">
    <br>
    <p>Have an account? <a href="{% url 'login' %}">Login</a></p>
  </form>
</div>

  {% endblock content %}